### ISSUE TITLE
Smartping 运行数十秒后自动停止

### ISSUE THREAD

**Issue by 66q** [smartping/smartping#42]
ubuntu@lax:~/smartping$ ./control run
2018-04-30/13:46:37 [Info] config.go Config loaded
2018-04-30/13:46:37 [Info] http.go [func:StartHttp] startin
 to listen on 8899
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-127.0.0.1` Start..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-127.0.0.1` Finish..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-93.46.8.89` Start..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-93.46.8.89` Finish..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-220.181.57.217` Start..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-220.181.57.217` Finish..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-114.114.114.114` Start..
2018-04-30/13:46:37 [Info] storage.go [func:CreatePingTable
 CreateDB `pinglog-114.114.114.114` Finish..
panic: runtime error: invalid memory address or nil pointer
dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 p
=0x6b9176]

goroutine 71 [running]:
_/root/smartping_v0.5.0/src/nettools.(*pkg).Send(0xc42009bd
0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/smartping_v0.5.0/src/nettools/icmp.go:41 +0xf
_/root/smartping_v0.5.0/src/nettools.RunPing(0xc4200e60e0,
xf, 0xb2d05e00, 0x40, 0x0, 0x8f76f9, 0x2, 0xc4201d06e0)
        /root/smartping_v0.5.0/src/nettools/ping.go:28 +0x3
5
_/root/smartping_v0.5.0/src/funcs.StartPing(0xc4200e60da, 0
6, 0xc4200e60e0, 0xf, 0xc4200e60f0, 0x2, 0x1e, 0x3, 0xc8, 0
32, ...)
        /root/smartping_v0.5.0/src/funcs/ping.go:20 +0x1d6
created by main.main.func1
        /root/smartping_v0.5.0/src/smartping.go:37 +0x14b

**Comment by 66q** [comment]
系统 Ubuntu 16.04 LTS
内核 4.13.0-39-generic

**Comment by hi-august** [comment]
same issue
系统 Ubuntu 15.10
内核 4.2.0-16-generic

**Comment by toryzen** [comment]
切换到root执行或者sudo执行

**Comment by hi-august** [comment]
@toryzen Thanks

**Comment by 66q** [comment]
问题已经解决，但还是希望能在普通用户下运行以确保安全。
