### ISSUE TITLE
Ubuntu 20.04 运行时崩溃

### ISSUE THREAD

**Issue by EkkoG** [smartping/smartping#87]
环境：Ubuntu 20.04
版本：0.8.0
配置：默认配置
日志

2020-11-16/06:14:06 [Info] config.go Config loaded
2020-11-16/06:14:06 [Info] http.go [func:StartHttp] starting to listen on 8899
2020-11-16/06:14:06 [Info] archive.go [func:ClearArchive] starting run ClearArchive
2020-11-16/06:14:06 [Info] archive.go [func:ClearArchive] ClearArchive Finish
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ac968]

goroutine 28 [running]:
github.com/smartping/smartping/src/nettools.(*pkg).Send(0xc000052c88, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/go/src/github.com/smartping/smartping/src/nettools/ping.go:42 +0xf8
github.com/smartping/smartping/src/nettools.RunPing(0xc0001106f0, 0xb2d05e00, 0x40, 0x0, 0xc0001106f0, 0x0, 0x0)
        /root/go/src/github.com/smartping/smartping/src/nettools/ping.go:124 +0x1d0
github.com/smartping/smartping/src/funcs.MappingTask(0xc0000292e4, 0x6, 0xc0000292e0, 0x4, 0xc00005d8c0, 0x1, 0x4, 0xc000029500)
        /root/go/src/github.com/smartping/smartping/src/funcs/mapping.go:51 +0x9bd
created by github.com/smartping/smartping/src/funcs.Mapping
        /root/go/src/github.com/smartping/smartping/src/funcs/mapping.go:30 +0x3bd

**Comment by ChenYue1030** [comment]
这个问题处理了吗
