### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by shenghuofei** [smartping/smartping#98]
系统： centos 7
我下载最新版tar包，解压启动后报错，是代码问题还是默认配置要修改呢，报错如下：
2022-08-12/11:01:01 [Info] archive.go [func:ClearArchive] ClearArchive Finish
2022-08-12/11:02:00 [Info] mapping.go Start MappingTask 浙江 cucc..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ac968]

goroutine 65 [running]:
github.com/smartping/smartping/src/nettools.(*pkg).Send(0xc00019bc88, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/smartping/smartping/src/nettools/ping.go:42 +0xf8
github.com/smartping/smartping/src/nettools.RunPing(0xc0001782a0, 0xb2d05e00, 0x40, 0x0, 0xc0001782a0, 0x0, 0x0)
	/root/go/src/github.com/smartping/smartping/src/nettools/ping.go:124 +0x1d0
github.com/smartping/smartping/src/funcs.MappingTask(0xc000027304, 0x6, 0xc000027300, 0x4, 0xc0000918c0, 0x1, 0x4, 0xc0001c20c0)
	/root/go/src/github.com/smartping/smartping/src/funcs/mapping.go:51 +0x9bd
created by github.com/smartping/smartping/src/funcs.Mapping
	/root/go/src/github.com/smartping/smartping/src/funcs/mapping.go:30 +0x3bd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7ac968]

goroutine 67 [running]:
github.com/smartping/smartping/src/nettools.(*pkg).Send(0xc00007ddd0, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/src/github.com/smartping/smartping/src/nettools/ping.go:42 +0xf8
github.com/smartping/smartping/src/nettools.RunPing(0xc000158510, 0xb2d05e00, 0x40, 0x0, 0xc000158510, 0x0, 0x0)
	/root/go/src/github.com/smartping/smartping/src/nettools/ping.go:124 +0x1d0
github.com/smartping/smartping/src/funcs.PingTask(0xc0000271e0, 0x9, 0xc0000271b8, 0x7, 0x0, 0x1054940, 0x0, 0x0, 0x1054940, 0x0, ...)
	/root/go/src/github.com/smartping/smartping/src/funcs/ping.go:34 +0x25e
created by github.com/smartping/smartping/src/funcs.Ping
	/root/go/src/github.com/smartping/smartping/src/funcs/ping.go:18 +0x170

**Comment by main1015** [comment]
同样的问题
